

ARG VERSION

FROM alpine:${VERSION} as stage1

ARG DATE
RUN echo ${DATE}
RUN echo ${TIME}

ARG TIME
RUN echo ${DATE}
RUN echo ${TIME}

FROM alpine:${VERSION} as stage2

RUN echo ${DATE}
RUN echo ${TIME}






